[package]
name = "mqrstt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.37"

bytes = "1.2.1"

bitflags = "1.3.2"

tracing = "0.1.37"

async-channel = "1.8.0"
async-mutex = "1.4.0"
futures-concurrency = "7.0.0"
futures = { version = "0.3.25" }

#quinn = "0.9.0"

tokio = { version = "1.21", features = ["macros", "io-util", "net", "time"] }

[dev-dependencies]
tokio = { version = "1.21", features = ["rt-multi-thread", "rt", "macros", "sync", "io-util", "net", "time"] }
pretty_assertions = "1.3.0"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }