[package]
name = "mqrstt"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["smol", "tokio", "tcp", "tokio-rustls", "smol-rustls"]
tokio = ["dep:tokio"]
smol = ["dep:smol"]
tcp = []
tokio-rustls = ["dep:tokio-rustls", "dep:rustls", "dep:rustls-pemfile", "dep:webpki"]
smol-rustls = ["dep:async-rustls", "dep:rustls", "dep:rustls-pemfile", "dep:webpki"]

# If in the future we only provide an MQTT packet handler to make it async, sync and runtime agnostic
# then this is not needed
# quic = ["dep:quinn"]
# native-tls = ["dep:async-native-tls"]

[dependencies]
# Packets
bytes = "1.2.1"
bitflags = "1.3.2"

# Errors
thiserror = "1.0.37"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }

async-channel = "1.8.0"
async-mutex = "1.4.0"
futures-concurrency = "7.0.0"

# Needed for all TLS
rustls = { version = "0.20.7", optional = true }
rustls-pemfile = { version = "1.0.1", optional = true }
webpki = { version = "0.22.0", optional = true }

# quic feature flag
quinn = {version = "0.9.0", optional = true }

# tokio feature flag
tokio = { version = "1.21", features = ["macros", "io-util", "net", "time"], optional = true }
tokio-rustls = { version = "0.23.4", optional = true }

# smol feature flag
smol = { version = "1.3.0", optional = true }
async-rustls = { version = "0.3.0", optional = true }
#async-native-tls = { version = "0.4.0", optional = true }

[dev-dependencies]
pretty_assertions = "1.3.0"
tokio = { version = "1.21", features = ["rt-multi-thread", "rt", "macros", "sync", "io-util", "net", "time"] }
smol = { version = "1.3.0" }
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }