[package]
name = "mqrstt"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["smol", "rust-tls"]
tokio = ["dep:tokio"]
smol = ["dep:smol"]
tcp = []
native-tls = ["dep:async-native-tls"]
rust-tls = ["dep:async-rustls", "dep:rustls", "dep:rustls-pemfile"]
quic = ["dep:quinn"]


[dependencies]
# Packets
bytes = "1.2.1"
bitflags = "1.3.2"

# Errors
thiserror = "1.0.37"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }

async-channel = "1.8.0"
async-mutex = "1.4.0"
futures-concurrency = "7.0.0"

# TLS
rustls = { version = "0.20.7", optional = true }
async-rustls = { version = "0.3.0", optional = true }
rustls-pemfile = { version = "1.0.1", optional = true }

async-native-tls = { version = "0.4.0", optional = true }

# quic feature flag
quinn = {version = "0.9.0", optional = true }

# tokio feature flag
tokio = { version = "1.21", features = ["macros", "io-util", "net", "time"], optional = true }

# smol feature flag
smol = { version = "1.3.0", optional = true}

[dev-dependencies]
pretty_assertions = "1.3.0"
tokio = { version = "1.21", features = ["rt-multi-thread", "rt", "macros", "sync", "io-util", "net", "time"] }
smol = { version = "1.3.0" }
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }