[package]
name = "mqrstt"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["tokio"]
tokio = ["dep:tokio"]
smol = ["dep:smol"]
tcp = []
tls = []
quic = ["dep:quinn"]


[dependencies]
thiserror = "1.0.37"

bytes = "1.2.1"

bitflags = "1.3.2"

tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }

async-channel = "1.8.0"
async-mutex = "1.4.0"
futures-concurrency = "7.0.0"
#futures = { version = "0.3.25" }

# quic feature flag
quinn = {version = "0.9.0", optional = true }

# tokio feature flag
tokio = { version = "1.21", features = ["macros", "io-util", "net", "time"], optional = true }

# smol feature flag
smol = { version = "1.3.0", optional = true}
#async-net = { version = "1.7.0", optional = true }
#futures-lite = { verion = "1.12.0", optional = true}
#async-io = { verion = "1.12.0", optional = true}

[dev-dependencies]
pretty_assertions = "1.3.0"
tokio = { version = "1.21", features = ["rt-multi-thread", "rt", "macros", "sync", "io-util", "net", "time"] }
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }