[package]
name = "sync_tcp_v0_2_2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mqrstt = { version = "0.2.2", default-features = false, features = ["sync"]}
